import {
  CardList,
  CloseButton,
  ComponentProvider,
  ImageWrapper,
  PageHeader,
  PageWrapper,
  ParallaxCard,
  ProjectHeader,
  ProjectModal,
  ProjectRow,
  ProjectTabs,
  SocialLink,
  TextBlock,
  TextHeadline,
  TextWrapper,
  Typewriter,
  VideoWrapper,
} from '@/components/layout';

import MainPage from '@/components/pages/MainPage.vue';

export {
  CardList,
  CloseButton,
  ComponentProvider,
  ImageWrapper,
  MainPage,
  PageHeader,
  PageWrapper,
  ParallaxCard,
  ProjectHeader,
  ProjectModal,
  ProjectRow,
  ProjectTabs,
  SocialLink,
  TextBlock,
  TextHeadline,
  TextWrapper,
  Typewriter,
  VideoWrapper,
};
