import {
  CardList,
  CloseButton,
  ComponentProvider,
  ImageWrapper,
  PageHeader,
  PageWrapper,
  ParallaxCard,
  ProjectHeader,
  ProjectModal,
  ProjectRow as Row,
  Tabs,
  SocialLink,
  TextBlock,
  Headline,
  TextWrapper as Text,
  Typewriter,
  VideoWrapper,
} from '@/components/layout';

import MainPage from '@/components/pages/MainPage.vue';

export {
  CardList,
  CloseButton,
  ComponentProvider,
  ImageWrapper,
  MainPage,
  PageHeader,
  PageWrapper,
  ParallaxCard,
  ProjectHeader,
  ProjectModal,
  Row,
  Tabs,
  SocialLink,
  TextBlock,
  Headline,
  Text,
  Typewriter,
  VideoWrapper,
};
