const content = [
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Lorem ipsum Lorem ipsum',
    titleColor: 'white',
    project: 'Draft',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Canyons',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Canyons',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Geometry',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
    project: 'TestProject',
  },
];

export default content;