const content = [
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum ',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
  },
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Canyons',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
  },
  {
    bgImage: 'bg.png',
    fgImage: 'fg.png',
    title: 'Canyons',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-1.png',
    fgImage: 'fg-1.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-2.png',
    fgImage: 'fg-2.png',
    title: 'Beaches',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-3.png',
    fgImage: 'fg-3.png',
    title: 'Trees',
    titleColor: 'white',
  },
  {
    bgImage: 'bg-4.png',
    fgImage: 'fg-4.png',
    title: 'Trees',
    titleColor: 'white',
    'gradient-color': '77, 45, 45',
  },
  {
    bgImage: 'bg-5.png',
    fgImage: 'fg-5.png',
    title: 'Trees',
    titleColor: 'white',
  },
];

export default content;